### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by MarkySparky** [applicazza/docker-ionic3#1]
Hi, thanks for the dockerfile.

When I use this to build my ionic3 project on gitlab, I get this error in the console:

No installed build tools found. Install the Android build tools version 19.1.0 or higher.

Seems it cant find build tools. From googling around, looks like a problem with the android_home env variable, but I can see its being set in the dockerfile.

Any idea how to proceed with this?

Many thanks
Mark

**Comment by applicazza** [comment]
@MarkySparky 

Hi,

I've pushed an updated version of Dockerfile. Please try to build it against that one and, please, let me know whether you face the same issue or not.

Cheers,
Artyom.

**Comment by MarkySparky** [comment]
Will do. On train, wifi slow, but fingers crossed. Thanks

**Comment by MarkySparky** [comment]
Just realised I didn't get back to you. Really sorry about that.
Yes, it worked. Thanks very much indeed.
